"""Render validated deployment state into deterministic runtime files."""

import json
from importlib.resources import files
from pathlib import Path
from typing import Any

from .validation import Issue, LoadedProject, validate_project
from .yamlio import dump_mapping


class RenderError(ValueError):
    """Raised when runtime configuration cannot be rendered safely."""


def _require_valid(project: LoadedProject) -> None:
    failures = [issue for issue in validate_project(project) if issue.severity == "FAIL"]
    if failures:
        details = "; ".join(f"{issue.path}: {issue.message}" for issue in failures)
        raise RenderError(f"deployment project is not renderable: {details}")


def _runtime_config(
    bridge_domain: str,
    minecraft_domain: str,
    release_identity: str,
    *,
    connection_enabled: bool = True,
) -> dict[str, Any]:
    return {
        "bridge_url": f"wss://{bridge_domain}",
        "default_sandbox": minecraft_domain,
        "connection_enabled": connection_enabled,
        "release_identity": release_identity,
    }


def _minecraft_properties(config: dict[str, Any]) -> str:
    gameplay = config["gameplay"]
    world = config["world"]
    performance = config["performance"]
    motd = "\\n".join(config["identity"]["motd"])
    properties = {
        "allow-flight": "false",
        "difficulty": "hard",
        "enable-query": "false",
        "enable-rcon": "false",
        "enable-status": "true",
        "enforce-secure-profile": "true",
        "force-gamemode": str(gameplay["force_gamemode"]).lower(),
        "gamemode": gameplay["gamemode"],
        "hardcore": str(gameplay["hardcore"]).lower(),
        "log-ips": "true",
        "management-server-enabled": "false",
        "max-players": "18",
        "max-tick-time": str(performance["max_tick_time"]),
        "max-world-size": str(world["radius_blocks"]),
        "motd": motd,
        "network-compression-threshold": str(performance["network_compression_threshold"]),
        "online-mode": "true",
        "server-port": "25565",
        "simulation-distance": "6",
        "spawn-protection": str(world["spawn_protection_radius"]),
        "view-distance": "10",
        "white-list": "false",
    }
    return "# Generated by mcrctl. Do not edit.\n" + "".join(f"{key}={value}\n" for key, value in properties.items())


def _bridge_service(image: str, scratch_domain: str, sandbox_domain: str) -> dict[str, Any]:
    return {
        "image": image,
        "restart": "unless-stopped",
        "environment": {
            "BRIDGE_WS_HOST": "0.0.0.0",
            "BRIDGE_WS_PORT": "8080",
            "BRIDGE_ORIGIN_ALLOWLIST": f"https://{scratch_domain}",
            "BRIDGE_SANDBOX_ALLOWLIST": sandbox_domain,
            "BRIDGE_DEFAULT_SANDBOX": sandbox_domain,
            "BRIDGE_SANDBOX_PORT": "25575",
        },
        "networks": ["app"],
    }


def _minecraft_service(
    *,
    channel: str,
    image: str,
    minecraft: dict[str, Any],
    locked_minecraft: dict[str, Any],
    data_path: str,
    backup_path: str,
    artifact_volumes: list[str],
    sandbox_domain: str,
    timezone: str,
) -> dict[str, Any]:
    paper = locked_minecraft["paper"]
    return {
        "image": image,
        "profiles": [channel],
        "restart": "unless-stopped",
        "stop_grace_period": f"{minecraft['stop_grace_seconds']}s",
        "environment": {
            "TZ": timezone,
            "EULA": "TRUE",
            "TYPE": "PAPER",
            "VERSION": locked_minecraft["version"],
            "PAPER_CUSTOM_JAR": f"/artifacts/{paper['filename']}",
            "UID": str(minecraft["uid"]),
            "GID": str(minecraft["gid"]),
            "MEMORY": minecraft["memory"],
            "ENABLE_RCON": "false",
            "CREATE_CONSOLE_IN_PIPE": "true",
            "STOP_DURATION": str(minecraft["stop_grace_seconds"] - 10),
            "REMOVE_OLD_MODS": "true",
            "REMOVE_OLD_MODS_DEPTH": "1",
            "SKIP_DOWNLOAD_DEFAULTS": "true",
            "COPY_CONFIG_DEST": "/data",
            "SYNC_SKIP_NEWER_IN_DESTINATION": "false",
            "REPLACE_ENV_DURING_SYNC": "false",
        },
        "ports": [
            f"{minecraft['java_port']}:25565/tcp",
            f"{minecraft['bedrock_port']}:19132/udp",
            f"{minecraft['mcremote_port']}:25575/tcp",
        ],
        "volumes": [
            f"{data_path}:/data",
            f"{backup_path}:/backup",
            f"./minecraft-{channel}:/config:ro",
            *artifact_volumes,
        ],
        "networks": {"app": {"aliases": [sandbox_domain]}},
    }


def _artifact_volumes(
    artifact_root: str,
    config_plugins: dict[str, Any],
    locked: dict[str, Any],
) -> list[str]:
    paper = locked["minecraft"]["paper"]
    volumes = [f"{artifact_root}/sha256/{paper['sha256']}:/artifacts/{paper['filename']}:ro"]
    for plugin_name in config_plugins["enabled"]:
        artifact = locked["plugins"][plugin_name]
        volumes.append(f"{artifact_root}/sha256/{artifact['sha256']}:/plugins/{artifact['filename']}:ro")
    return volumes


def _compose(project: LoadedProject) -> dict[str, Any]:
    config = project.config
    lock = project.lock
    domains = config["domains"]
    host_paths = config["host"]["paths"]
    images = lock["images"]
    beta = config["beta"]
    homepage = lock["homepage"]
    artifact_root = host_paths["artifacts"].rstrip("/")

    services: dict[str, Any] = {
        "caddy": {
            "image": images["caddy"],
            "restart": "unless-stopped",
            "cap_drop": ["ALL"],
            "cap_add": ["NET_BIND_SERVICE"],
            "ports": ["80:80/tcp", "443:443/tcp"],
            "volumes": [
                "./Caddyfile:/etc/caddy/Caddyfile:ro",
                f"{host_paths['caddy']}/data:/data",
                f"{host_paths['caddy']}/config:/config",
                f"{host_paths['homepage'].rstrip('/')}/sha256/{homepage['sha256']}:/srv/homepage:ro",
            ],
            "networks": ["edge", "app"],
        },
        "scratch-stable": {
            "image": images["scratch_stable"],
            "restart": "unless-stopped",
            "volumes": ["./runtime/stable.json:/usr/share/nginx/html/mc-remote-runtime-config.json:ro"],
            "networks": ["app"],
        },
        "scratch-beta": {
            "image": images["scratch_beta"],
            "restart": "unless-stopped",
            "volumes": ["./runtime/beta.json:/usr/share/nginx/html/mc-remote-runtime-config.json:ro"],
            "networks": ["app"],
        },
        "bridge-stable": _bridge_service(images["bridge"], domains["scratch"], domains["minecraft"]),
        "bridge-beta": _bridge_service(images["bridge"], domains["scratch_beta"], beta["domain"]),
        "minecraft-stable": _minecraft_service(
            channel="stable",
            image=images["minecraft"],
            minecraft=config["minecraft"],
            locked_minecraft=lock["minecraft"],
            data_path=host_paths["minecraft"],
            backup_path=host_paths["backup"],
            artifact_volumes=_artifact_volumes(artifact_root, config["plugins"], lock),
            sandbox_domain=domains["minecraft"],
            timezone=config["deployment"]["timezone"],
        ),
    }

    if beta.get("enabled") is True:
        services["minecraft-beta"] = _minecraft_service(
            channel="beta",
            image=lock["beta"]["image"],
            minecraft=beta["minecraft"],
            locked_minecraft=lock["beta"]["minecraft"],
            data_path=beta["paths"]["minecraft"],
            backup_path=beta["paths"]["backup"],
            artifact_volumes=_artifact_volumes(artifact_root, beta["plugins"], lock["beta"]),
            sandbox_domain=beta["domain"],
            timezone=config["deployment"]["timezone"],
        )

    return {
        "name": "mc-remote",
        "services": services,
        "networks": {"edge": {}, "app": {"internal": False}},
    }


def render_project(project: LoadedProject, output: Path) -> list[Path]:
    _require_valid(project)
    output = output.resolve()
    (output / "runtime").mkdir(parents=True, exist_ok=True)
    (output / "bridge").mkdir(parents=True, exist_ok=True)
    (output / "minecraft-stable" / "plugins" / "ServerBackup").mkdir(parents=True, exist_ok=True)

    config = project.config
    lock = project.lock
    domains = config["domains"]
    stable_runtime = _runtime_config(domains["bridge"], domains["minecraft"], lock["images"]["scratch_stable"])
    beta = config["beta"]
    beta_enabled = beta.get("enabled") is True
    beta_runtime = _runtime_config(
        domains["bridge_beta"],
        beta["domain"],
        lock["images"]["scratch_beta"],
        connection_enabled=beta_enabled,
    )
    if beta_enabled:
        (output / "minecraft-beta" / "plugins" / "ServerBackup").mkdir(parents=True, exist_ok=True)
        (output / "operations").mkdir(parents=True, exist_ok=True)

    compose_path = output / "compose.yaml"
    dump_mapping(compose_path, _compose(project))

    caddyfile = output / "Caddyfile"
    homepage_domains = ", ".join([domains["homepage"], *domains["homepage_aliases"]])
    caddyfile.write_text(
        f"""{homepage_domains} {{
    root * /srv/homepage
    encode zstd gzip
    file_server
}}

{domains["scratch"]} {{
    reverse_proxy scratch-stable:8080
}}

{domains["scratch_beta"]} {{
    reverse_proxy scratch-beta:8080
}}

{domains["bridge"]} {{
    reverse_proxy bridge-stable:8080
}}

{domains["bridge_beta"]} {{
    reverse_proxy bridge-beta:8080
}}
""",
        encoding="utf-8",
    )

    stable_path = output / "runtime" / "stable.json"
    beta_path = output / "runtime" / "beta.json"
    stable_path.write_text(json.dumps(stable_runtime, indent=2) + "\n", encoding="utf-8")
    beta_path.write_text(json.dumps(beta_runtime, indent=2) + "\n", encoding="utf-8")

    routes_path = output / "bridge" / "routes.yml"
    routes = {domains["minecraft"]: {"host": "minecraft-stable", "port": 25575}}
    if beta_enabled:
        routes[beta["domain"]] = {"host": "minecraft-beta", "port": 25575}
    dump_mapping(routes_path, {"routes": routes})

    backup = config["backup"]
    server_backup_path = output / "minecraft-stable" / "plugins" / "ServerBackup" / "config.yml"
    dump_mapping(
        server_backup_path,
        {
            "AutomaticBackups": True,
            "BackupTimer": {
                "Days": [
                    "MONDAY",
                    "TUESDAY",
                    "WEDNESDAY",
                    "THURSDAY",
                    "FRIDAY",
                    "SATURDAY",
                    "SUNDAY",
                ],
                "Times": [value.replace(":", "-") for value in backup["times"]],
            },
            "BackupWorlds": [backup["source"]],
            "DeleteOldBackups": 0,
            "BackupLimiter": 0,
            "KeepUniqueBackups": False,
            "UpdateAvailableMessage": True,
            "AutomaticUpdates": False,
            "BackupDestination": backup["output"],
            "Ftp": {"UploadBackup": False, "DeleteLocalBackup": False},
        },
    )

    server_properties_path = output / "minecraft-stable" / "server.properties"
    server_properties_path.write_text(_minecraft_properties(config), encoding="utf-8")

    bukkit_path = output / "minecraft-stable" / "bukkit.yml"
    dump_mapping(bukkit_path, {"settings": {"connection-throttle": 4000}})

    spigot_path = output / "minecraft-stable" / "spigot.yml"
    dump_mapping(spigot_path, {"settings": {"restart-on-crash": False, "restart-script": ""}})

    beta_paths: list[Path] = []
    if beta_enabled:
        beta_backup = beta["backup"]
        beta_server_backup_path = output / "minecraft-beta" / "plugins" / "ServerBackup" / "config.yml"
        dump_mapping(
            beta_server_backup_path,
            {
                "AutomaticBackups": True,
                "BackupTimer": {
                    "Days": [
                        "MONDAY",
                        "TUESDAY",
                        "WEDNESDAY",
                        "THURSDAY",
                        "FRIDAY",
                        "SATURDAY",
                        "SUNDAY",
                    ],
                    "Times": [value.replace(":", "-") for value in beta_backup["times"]],
                },
                "BackupWorlds": [beta_backup["source"]],
                "DeleteOldBackups": 0,
                "BackupLimiter": 0,
                "KeepUniqueBackups": False,
                "UpdateAvailableMessage": True,
                "AutomaticUpdates": False,
                "BackupDestination": beta_backup["output"],
                "Ftp": {"UploadBackup": False, "DeleteLocalBackup": False},
            },
        )
        beta_properties_path = output / "minecraft-beta" / "server.properties"
        beta_properties_path.write_text(_minecraft_properties(config), encoding="utf-8")
        beta_bukkit_path = output / "minecraft-beta" / "bukkit.yml"
        dump_mapping(beta_bukkit_path, {"settings": {"connection-throttle": 4000}})
        beta_spigot_path = output / "minecraft-beta" / "spigot.yml"
        dump_mapping(beta_spigot_path, {"settings": {"restart-on-crash": False, "restart-script": ""}})
        operation_paths = []
        assets = files("mc_remote_stack").joinpath("assets")
        for filename in ("use-beta.sh", "use-stable.sh"):
            operation_path = output / "operations" / filename
            operation_path.write_text(assets.joinpath(filename).read_text(encoding="utf-8"), encoding="utf-8")
            operation_path.chmod(0o755)
            operation_paths.append(operation_path)
        beta_paths = [
            beta_server_backup_path,
            beta_properties_path,
            beta_bukkit_path,
            beta_spigot_path,
            *operation_paths,
        ]

    return [
        compose_path,
        caddyfile,
        stable_path,
        beta_path,
        routes_path,
        server_backup_path,
        server_properties_path,
        bukkit_path,
        spigot_path,
        *beta_paths,
    ]


def render_issues(project: LoadedProject) -> list[Issue]:
    """Expose render blockers using the common issue contract."""
    return validate_project(project)
