"""Render validated deployment state into deterministic runtime files."""

import json
from pathlib import Path
from typing import Any

from .validation import Issue, LoadedProject, validate_project
from .yamlio import dump_mapping


class RenderError(ValueError):
    """Raised when runtime configuration cannot be rendered safely."""


def _require_valid(project: LoadedProject) -> None:
    failures = [issue for issue in validate_project(project) if issue.severity == "FAIL"]
    if failures:
        details = "; ".join(f"{issue.path}: {issue.message}" for issue in failures)
        raise RenderError(f"deployment project is not renderable: {details}")


def _runtime_config(bridge_domain: str, minecraft_domain: str, release_identity: str) -> dict[str, Any]:
    return {
        "bridge_url": f"wss://{bridge_domain}",
        "default_sandbox": minecraft_domain,
        "connection_enabled": True,
        "release_identity": release_identity,
    }


def _minecraft_properties(config: dict[str, Any]) -> str:
    gameplay = config["gameplay"]
    world = config["world"]
    performance = config["performance"]
    motd = "\\n".join(config["identity"]["motd"])
    properties = {
        "allow-flight": "false",
        "difficulty": "hard",
        "enable-query": "false",
        "enable-rcon": "false",
        "enable-status": "true",
        "enforce-secure-profile": "true",
        "force-gamemode": str(gameplay["force_gamemode"]).lower(),
        "gamemode": gameplay["gamemode"],
        "hardcore": str(gameplay["hardcore"]).lower(),
        "log-ips": "true",
        "management-server-enabled": "false",
        "max-players": "18",
        "max-tick-time": str(performance["max_tick_time"]),
        "max-world-size": str(world["radius_blocks"]),
        "motd": motd,
        "network-compression-threshold": str(performance["network_compression_threshold"]),
        "online-mode": "true",
        "server-port": "25565",
        "simulation-distance": "6",
        "spawn-protection": str(world["spawn_protection_radius"]),
        "view-distance": "10",
        "white-list": "false",
    }
    return "# Generated by mcrctl. Do not edit.\n" + "".join(f"{key}={value}\n" for key, value in properties.items())


def _compose(project: LoadedProject) -> dict[str, Any]:
    config = project.config
    lock = project.lock
    host_paths = config["host"]["paths"]
    minecraft = config["minecraft"]
    images = lock["images"]
    locked_minecraft = lock["minecraft"]
    paper = locked_minecraft["paper"]
    homepage = lock["homepage"]
    artifact_root = host_paths["artifacts"].rstrip("/")
    artifact_volumes = [
        f"{artifact_root}/sha256/{paper['sha256']}:/artifacts/{paper['filename']}:ro",
    ]
    for plugin_name in config["plugins"]["enabled"]:
        artifact = lock["plugins"][plugin_name]
        artifact_volumes.append(
            f"{artifact_root}/sha256/{artifact['sha256']}:/plugins/{artifact['filename']}:ro"
        )

    return {
        "name": "mc-remote",
        "services": {
            "caddy": {
                "image": images["caddy"],
                "restart": "unless-stopped",
                "cap_drop": ["ALL"],
                "cap_add": ["NET_BIND_SERVICE"],
                "ports": ["80:80/tcp", "443:443/tcp"],
                "volumes": [
                    "./Caddyfile:/etc/caddy/Caddyfile:ro",
                    f"{host_paths['caddy']}/data:/data",
                    f"{host_paths['caddy']}/config:/config",
                    f"{host_paths['homepage'].rstrip('/')}/sha256/{homepage['sha256']}:/srv/homepage:ro",
                ],
                "networks": ["edge", "app"],
            },
            "scratch-stable": {
                "image": images["scratch_stable"],
                "restart": "unless-stopped",
                "volumes": [
                    "./runtime/stable.json:/usr/share/nginx/html/mc-remote-runtime-config.json:ro",
                ],
                "networks": ["app"],
            },
            "scratch-dev": {
                "image": images["scratch_dev"],
                "restart": "unless-stopped",
                "volumes": [
                    "./runtime/dev.json:/usr/share/nginx/html/mc-remote-runtime-config.json:ro",
                ],
                "networks": ["app"],
            },
            "bridge": {
                "image": images["bridge"],
                "restart": "unless-stopped",
                "environment": {
                    "BRIDGE_WS_HOST": "0.0.0.0",
                    "BRIDGE_WS_PORT": "8080",
                    "BRIDGE_ORIGIN_ALLOWLIST": (
                        f"https://{config['domains']['scratch']},https://{config['domains']['scratch_dev']}"
                    ),
                    "BRIDGE_SANDBOX_ALLOWLIST": config["domains"]["minecraft"],
                    "BRIDGE_DEFAULT_SANDBOX": config["domains"]["minecraft"],
                    "BRIDGE_SANDBOX_PORT": "25575",
                },
                "networks": ["app"],
            },
            "minecraft": {
                "image": images["minecraft"],
                "restart": "unless-stopped",
                "stop_grace_period": f"{minecraft['stop_grace_seconds']}s",
                "environment": {
                    "EULA": "TRUE",
                    "TYPE": "PAPER",
                    "VERSION": locked_minecraft["version"],
                    "PAPER_CUSTOM_JAR": f"/artifacts/{paper['filename']}",
                    "UID": str(minecraft["uid"]),
                    "GID": str(minecraft["gid"]),
                    "MEMORY": minecraft["memory"],
                    "ENABLE_RCON": "false",
                    "CREATE_CONSOLE_IN_PIPE": "true",
                    "STOP_DURATION": str(minecraft["stop_grace_seconds"] - 10),
                    "REMOVE_OLD_MODS": "true",
                    "REMOVE_OLD_MODS_DEPTH": "1",
                    "SKIP_DOWNLOAD_DEFAULTS": "true",
                    "COPY_CONFIG_DEST": "/data",
                    "SYNC_SKIP_NEWER_IN_DESTINATION": "false",
                    "REPLACE_ENV_DURING_SYNC": "false",
                },
                "ports": [
                    f"{minecraft['java_port']}:25565/tcp",
                    f"{minecraft['bedrock_port']}:19132/udp",
                    f"{minecraft['mcremote_port']}:25575/tcp",
                ],
                "volumes": [
                    f"{host_paths['minecraft']}:/data",
                    f"{host_paths['backup']}:/backup",
                    "./minecraft:/config:ro",
                    *artifact_volumes,
                ],
                "networks": {
                    "app": {
                        "aliases": [config["domains"]["minecraft"]],
                    }
                },
            },
        },
        "networks": {
            "edge": {},
            "app": {"internal": False},
        },
    }


def render_project(project: LoadedProject, output: Path) -> list[Path]:
    _require_valid(project)
    output = output.resolve()
    (output / "runtime").mkdir(parents=True, exist_ok=True)
    (output / "bridge").mkdir(parents=True, exist_ok=True)
    (output / "minecraft" / "plugins" / "ServerBackup").mkdir(parents=True, exist_ok=True)

    config = project.config
    lock = project.lock
    domains = config["domains"]
    stable_runtime = _runtime_config(domains["bridge"], domains["minecraft"], lock["images"]["scratch_stable"])
    dev_runtime = _runtime_config(domains["bridge"], domains["minecraft"], lock["images"]["scratch_dev"])

    compose_path = output / "compose.yaml"
    dump_mapping(compose_path, _compose(project))

    caddyfile = output / "Caddyfile"
    homepage_domains = ", ".join([domains["homepage"], *domains["homepage_aliases"]])
    caddyfile.write_text(
        f"""{homepage_domains} {{
    root * /srv/homepage
    encode zstd gzip
    file_server
}}

{domains['scratch']} {{
    reverse_proxy scratch-stable:8080
}}

{domains['scratch_dev']} {{
    reverse_proxy scratch-dev:8080
}}

{domains['bridge']} {{
    reverse_proxy bridge:8080
}}
""",
        encoding="utf-8",
    )

    stable_path = output / "runtime" / "stable.json"
    dev_path = output / "runtime" / "dev.json"
    stable_path.write_text(json.dumps(stable_runtime, indent=2) + "\n", encoding="utf-8")
    dev_path.write_text(json.dumps(dev_runtime, indent=2) + "\n", encoding="utf-8")

    routes_path = output / "bridge" / "routes.yml"
    dump_mapping(
        routes_path,
        {
            "routes": {
                domains["minecraft"]: {
                    "host": "minecraft",
                    "port": 25575,
                }
            }
        },
    )

    backup = config["backup"]
    server_backup_path = output / "minecraft" / "plugins" / "ServerBackup" / "config.yml"
    dump_mapping(
        server_backup_path,
        {
            "AutomaticBackups": True,
            "BackupTimer": {
                "Days": [
                    "MONDAY",
                    "TUESDAY",
                    "WEDNESDAY",
                    "THURSDAY",
                    "FRIDAY",
                    "SATURDAY",
                    "SUNDAY",
                ],
                "Times": [value.replace(":", "-") for value in backup["times"]],
            },
            "BackupWorlds": [backup["source"]],
            "DeleteOldBackups": 0,
            "BackupLimiter": 0,
            "KeepUniqueBackups": False,
            "UpdateAvailableMessage": True,
            "AutomaticUpdates": False,
            "BackupDestination": backup["output"],
            "Ftp": {"UploadBackup": False, "DeleteLocalBackup": False},
        },
    )

    server_properties_path = output / "minecraft" / "server.properties"
    server_properties_path.write_text(_minecraft_properties(config), encoding="utf-8")

    bukkit_path = output / "minecraft" / "bukkit.yml"
    dump_mapping(bukkit_path, {"settings": {"connection-throttle": 4000}})

    spigot_path = output / "minecraft" / "spigot.yml"
    dump_mapping(spigot_path, {"settings": {"restart-on-crash": False, "restart-script": ""}})

    return [
        compose_path,
        caddyfile,
        stable_path,
        dev_path,
        routes_path,
        server_backup_path,
        server_properties_path,
        bukkit_path,
        spigot_path,
    ]


def render_issues(project: LoadedProject) -> list[Issue]:
    """Expose render blockers using the common issue contract."""
    return validate_project(project)
