import hashlib
import inspect
from importlib.resources import files
from pathlib import Path

import pytest

from mc_remote_stack.cli import build_parser
from mc_remote_stack.composition import (
    CompositionContractError,
    DiscoveredPlugin,
    OverlayComposition,
    _inspect_overlay_composition,
    _plan_canonical_composition_locked,
    _prepare_composition_candidate,
    _validate_composition_transition,
)
from mc_remote_stack.deployment_update import _plan_deployment_update_locked
from mc_remote_stack.runtime_content import import_homepage_tree
from mc_remote_stack.toml_project import init_toml_project, load_order


def test_transaction_prepare_cleanup_never_uses_an_absolute_path_sentinel() -> None:
    for function in (
        _plan_deployment_update_locked,
        _plan_canonical_composition_locked,
    ):
        assert "/__moved__" not in inspect.getsource(function)


def _source_lock(tmp_path: Path) -> dict:
    routes = {
        "homepage": "mc-remote.com",
        "homepage_aliases": ["www.mc-remote.com"],
        "scratch": "scratch-beta.mc-remote.com",
        "bridge": "bridge-beta.mc-remote.com",
        "minecraft": "sb-beta.mc-remote.com",
        "wirescope": "wirescope-beta.mc-remote.com",
    }
    return {
        "runtime": {"artifact_store": str(tmp_path / "artifacts")},
        "components": [
            {
                "id": "mcremote",
                "role": "mcremote-plugin",
                "artifact": "mcremote-jar",
            }
        ],
        "artifacts": [
            {
                "id": "mcremote-jar",
                "kind": "https-file",
                "filename": "mc-remote-b4.jar",
                "sha256": "f" * 64,
            }
        ],
        "operator_inputs": [
            {
                "role": "public-routes",
                "adapter": "public-routes@2",
                "path": "operator/public-routes/routes.toml",
                "semantic_sha256": "e" * 64,
                "semantic": routes,
            }
        ],
    }


def _write_realistic_overlays(tmp_path: Path) -> tuple[Path, Path, Path]:
    recovery = tmp_path / "recovery"
    plugins = recovery / "plugins"
    plugins.mkdir(parents=True)
    worldedit = plugins / "worldedit-bukkit-7.4.2.jar"
    worldedit.write_bytes(b"worldedit exact\n")
    backup = tmp_path / "backup"
    backup.mkdir()
    external_config = tmp_path / "runtime-config"
    (external_config / "plugins" / "McRemote").mkdir(parents=True)
    (external_config / "plugins" / "McRemote" / "config.yml").write_text(
        "auth:\n  enforcement: true\n",
        encoding="utf-8",
    )
    generated = tmp_path / "generated"
    (generated / "minecraft" / "plugins" / "McRemote").mkdir(parents=True)
    (generated / "minecraft" / "plugins" / "McRemote" / "config.yml").write_text(
        "auth:\n  enforcement: true\n",
        encoding="utf-8",
    )
    homepage = recovery / "homepage" / "sha256" / ("a" * 64)
    homepage.mkdir(parents=True)
    (homepage / "index.html").write_text("homepage\n", encoding="utf-8")
    caddyfile = recovery / "Caddyfile.homepage"
    caddyfile.write_text(
        '''# Generated by mcrctl compose@4. Do not edit.
mc-remote.com, www.mc-remote.com {
    root * /srv/homepage
    encode zstd gzip
    file_server
}

scratch-beta.mc-remote.com {
    reverse_proxy scratch:8080
}

bridge-beta.mc-remote.com {
    reverse_proxy bridge:8080
}
''',
        encoding="utf-8",
    )
    plugin_overlay = recovery / "compose.recovery-plugins.yaml"
    plugin_overlay.write_text(
        f'''services:
  minecraft:
    volumes:
      - type: bind
        source: {external_config}
        target: /config
        read_only: true
      - type: bind
        source: {worldedit}
        target: /plugins/{worldedit.name}
        read_only: true
      - type: bind
        source: {backup}
        target: /backup
''',
        encoding="utf-8",
    )
    homepage_overlay = recovery / "compose.homepage.yaml"
    homepage_overlay.write_text(
        f'''services:
  caddy:
    volumes:
      - type: bind
        source: {caddyfile}
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: bind
        source: {homepage}
        target: /srv/homepage
        read_only: true
''',
        encoding="utf-8",
    )
    return generated, plugin_overlay, homepage_overlay


def test_overlay_inspection_recognizes_the_exact_public_runtime_composition(
    tmp_path: Path,
) -> None:
    generated, plugin_overlay, homepage_overlay = _write_realistic_overlays(tmp_path)

    inspected = _inspect_overlay_composition(
        (plugin_overlay, homepage_overlay),
        source_output=generated,
        source_lock=_source_lock(tmp_path),
    )

    assert len(inspected.plugins) == 1
    assert inspected.plugins[0].filename == "worldedit-bukkit-7.4.2.jar"
    assert inspected.plugins[0].sha256 == hashlib.sha256(b"worldedit exact\n").hexdigest()
    assert inspected.homepage_source.name == "a" * 64
    assert inspected.backup_path == tmp_path / "backup"
    assert inspected.external_config_path == tmp_path / "runtime-config"


def test_overlay_inspection_accepts_the_pre_wirescope_public_route_input(
    tmp_path: Path,
) -> None:
    generated, plugin_overlay, homepage_overlay = _write_realistic_overlays(tmp_path)
    source_lock = _source_lock(tmp_path)
    routes = source_lock["operator_inputs"][0]
    routes["adapter"] = "public-routes@1"
    routes["semantic"].pop("wirescope")

    inspected = _inspect_overlay_composition(
        (plugin_overlay, homepage_overlay),
        source_output=generated,
        source_lock=source_lock,
    )

    assert len(inspected.plugins) == 1
    assert inspected.homepage_source.name == "a" * 64


def test_overlay_inspection_rejects_unknown_service_mutation(tmp_path: Path) -> None:
    generated, plugin_overlay, homepage_overlay = _write_realistic_overlays(tmp_path)
    plugin_overlay.write_text(
        plugin_overlay.read_text(encoding="utf-8")
        + "    environment:\n      UNKNOWN: value\n",
        encoding="utf-8",
    )

    with pytest.raises(CompositionContractError) as exc_info:
        _inspect_overlay_composition(
            (plugin_overlay, homepage_overlay),
            source_output=generated,
            source_lock=_source_lock(tmp_path),
        )

    assert exc_info.value.reason == "composition_overlay_unknown"


def test_overlay_inspection_rejects_whole_plugin_directory_mount(tmp_path: Path) -> None:
    generated, plugin_overlay, homepage_overlay = _write_realistic_overlays(tmp_path)
    plugin_overlay.write_text(
        f'''services:
  minecraft:
    volumes:
      - type: bind
        source: {tmp_path / "recovery" / "plugins"}
        target: /plugins
        read_only: true
''',
        encoding="utf-8",
    )

    with pytest.raises(CompositionContractError) as exc_info:
        _inspect_overlay_composition(
            (plugin_overlay, homepage_overlay),
            source_output=generated,
            source_lock=_source_lock(tmp_path),
        )

    assert exc_info.value.reason == "composition_plugin_directory_forbidden"


def test_overlay_inspection_rejects_external_config_drift(tmp_path: Path) -> None:
    generated, plugin_overlay, homepage_overlay = _write_realistic_overlays(tmp_path)
    external = tmp_path / "runtime-config" / "plugins" / "McRemote" / "config.yml"
    external.write_text("auth:\n  enforcement: false\n", encoding="utf-8")

    with pytest.raises(CompositionContractError) as exc_info:
        _inspect_overlay_composition(
            (plugin_overlay, homepage_overlay),
            source_output=generated,
            source_lock=_source_lock(tmp_path),
        )

    assert exc_info.value.reason == "composition_external_config_drift"


def test_composition_candidate_converges_release_routes_and_typed_inputs(
    tmp_path: Path,
) -> None:
    source = init_toml_project(
        tmp_path / "deployment",
        deployment_name="official-public-beta",
        profile="vps-server@8",
        environment_identity="official-public-beta",
        channel="beta",
        exposure="public",
        purpose="integration",
        preset="public-web-paper@3",
        artifact_store=str(tmp_path / "artifacts"),
        runtime_volumes={
            "caddy-config": "caddy-config",
            "caddy-data": "caddy-data",
            "minecraft-data": "minecraft-data",
        },
        world_identity="world",
        bind_address="0.0.0.0",
        java_port=25565,
        mcremote_port=25575,
        minecraft_eula=True,
    ).root
    with (source / "mc-remote.toml").open("a", encoding="utf-8") as stream:
        stream.write(
            '''
[[operator_inputs]]
role = "public-routes"
adapter = "public-routes@1"
path = "operator/public-routes/routes.toml"

[[operator_inputs]]
role = "minecraft-server"
adapter = "minecraft-server@1"
path = "operator/minecraft-server/server.toml"

[[operator_inputs]]
role = "connection-targets"
adapter = "connection-targets@1"
path = "operator/connection-targets/targets.toml"
'''
        )
    routes = source / "operator/public-routes/routes.toml"
    routes.parent.mkdir(parents=True)
    routes.write_text(
        '''homepage = "mc-remote.com"
homepage_aliases = ["www.mc-remote.com"]
scratch = "scratch-beta.mc-remote.com"
bridge = "bridge-beta.mc-remote.com"
minecraft = "sb-beta.mc-remote.com"
''',
        encoding="utf-8",
    )
    server = source / "operator/minecraft-server/server.toml"
    server.parent.mkdir(parents=True)
    server.write_text('motd = "McRemote Sandbox Server"\n', encoding="utf-8")
    targets = source / "operator/connection-targets/targets.toml"
    targets.parent.mkdir(parents=True)
    targets.write_text(
        '''default_sandbox = "sb-beta.mc-remote.com"
[[targets]]
id = "beta"
label = "公開ベータ"
sandbox = "sb-beta.mc-remote.com"
''',
        encoding="utf-8",
    )
    output = source / "generated"
    output.mkdir()
    plugin_source = tmp_path / "WorldEdit.jar"
    plugin_source.write_bytes(b"worldedit\n")
    plugin = DiscoveredPlugin(
        "WorldEdit.jar",
        hashlib.sha256(plugin_source.read_bytes()).hexdigest(),
        plugin_source,
    )
    backup = tmp_path / "backup"
    backup.mkdir()
    homepage_source = tmp_path / "homepage"
    homepage_source.mkdir()
    (homepage_source / "index.html").write_text("home\n", encoding="utf-8")
    homepage = import_homepage_tree(homepage_source, tmp_path / "artifacts")
    composition = OverlayComposition(
        (plugin,),
        homepage_source,
        backup,
        None,
        (),
    )
    candidate = tmp_path / "candidate"

    _prepare_composition_candidate(
        source,
        output,
        candidate,
        target_profile="vps-server@10",
        target_preset="public-web-paper@4",
        input_overrides={
            ("public-routes", "wirescope"): "wirescope-beta.mc-remote.com"
        },
        data_root=files("mc_remote_stack").joinpath("data"),
        composition=composition,
        homepage=homepage,
    )

    order = load_order(candidate).order
    assert order["deployment"]["profile"] == "vps-server@10"
    assert order["environment"]["preset"] == "public-web-paper@4"
    inputs = {item["role"]: item for item in order["operator_inputs"]}
    assert set(inputs) == {
        "public-routes",
        "minecraft-server",
        "connection-targets",
        "minecraft-plugins",
        "homepage-static",
        "minecraft-backup",
    }
    assert inputs["public-routes"]["adapter"] == "public-routes@2"
    assert "wirescope-beta.mc-remote.com" in (
        candidate / "operator/public-routes/routes.toml"
    ).read_text(encoding="utf-8")
    assert "WorldEdit.jar" in (
        candidate / "operator/minecraft-plugins/plugins.toml"
    ).read_text(encoding="utf-8")
    assert str(backup) in (
        candidate / "operator/minecraft-backup/backup.toml"
    ).read_text(encoding="utf-8")


def _composition_transition_lock(*, target: bool) -> dict:
    lock = {
        "deployment": {"name": "official-public-beta"},
        "environment": {
            "identity": "official-public-beta",
            "channel": "beta",
            "exposure": "public",
            "purpose": "integration",
        },
        "input": {
            "profile": {"ref": "vps-server@10" if target else "vps-server@8"},
            "preset": {
                "ref": "public-web-paper@4" if target else "public-web-paper@3"
            },
        },
        "runtime": {
            "artifact_store": "/artifacts",
            "volumes": [
                {"role": "caddy-config", "identity": "caddy-config"},
                {"role": "caddy-data", "identity": "caddy-data"},
                {"role": "minecraft-data", "identity": "minecraft-data"},
            ],
        },
        "world": {"identity": "official-public-beta-world"},
        "network": {
            "bind_address": "0.0.0.0",
            "java_port": 25565,
            "mcremote_port": 25575,
        },
        "agreements": {"minecraft_eula": True},
        "secret_references": [],
        "render_plan": {
            "adapter": "compose@12" if target else "compose@10",
            "services": ["caddy", "scratch", "bridge", "minecraft"],
            "volume_roles": ["caddy-config", "caddy-data", "minecraft-data"],
            "required_security_controls": ["online-mode"],
        },
        "operator_inputs": [
            {"role": "public-routes", "path": "operator/public-routes/routes.toml"},
            {
                "role": "minecraft-server",
                "path": "operator/minecraft-server/server.toml",
            },
            {
                "role": "connection-targets",
                "path": "operator/connection-targets/targets.toml",
            },
        ],
    }
    if target:
        lock["render_plan"]["required_security_controls"].extend(
            [
                "exact-peripheral-plugin-set",
                "content-addressed-homepage",
                "explicit-backup-bind",
            ]
        )
        lock["operator_inputs"].extend(
            [
                {
                    "role": "minecraft-plugins",
                    "path": "operator/minecraft-plugins/plugins.toml",
                },
                {
                    "role": "homepage-static",
                    "path": "operator/homepage-static/homepage.toml",
                },
                {
                    "role": "minecraft-backup",
                    "path": "operator/minecraft-backup/backup.toml",
                },
            ]
        )
    return lock


def test_composition_transition_allows_one_reviewed_release_convergence() -> None:
    _validate_composition_transition(
        _composition_transition_lock(target=False),
        _composition_transition_lock(target=True),
    )


def test_composition_cli_accepts_release_and_route_convergence_inputs() -> None:
    args = build_parser().parse_args(
        [
            "deployment",
            "composition",
            "plan",
            "--project",
            "/deployment",
            "--to-profile",
            "vps-server@10",
            "--to-preset",
            "public-web-paper@4",
            "--set-input",
            "public-routes.wirescope=wirescope-beta.mc-remote.com",
        ]
    )

    assert args.to_preset == "public-web-paper@4"
    assert args.set_input == [
        "public-routes.wirescope=wirescope-beta.mc-remote.com"
    ]
